name: Process ENV and Run Terraform

on: 
  workflow_dispatch: 
  push:
    paths:
      - 'env-files/**'

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Execute Python script and capture outputs for Terraform environment variables
        run: |
          python ./output_exports.py > exports.sh
      
      - name: Set the environment variables from the Python script output
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < exports.sh
          rm exports.sh

      - name: Set up Terraform environment variables for AD_GROUP_ID and AD_GROUP_SECRET
        run: |
          echo "TF_VAR_ad_group_id=${{ secrets.AD_GROUP_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_ad_group_secret=${{ secrets.AD_GROUP_SECRET }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Extract Azure Credentials for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
      
      - name: Checkout Terraform Code Repository
        uses: actions/checkout@v4
        with:
          repository: 'Semal31/testSubAction-Code'
          path: 'testSubAction-Code'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
      
      - name: Terraform Init and Apply (pre)
        run: |
          terraform -chdir=./testSubAction-Code/pre init -backend-config="key=SubscriptionCreation/${{ env.TF_VAR_subscription_name }}/pre/terraform.tfstate"
          terraform -chdir=./testSubAction-Code/pre apply -auto-approve
      
      - name: Terraform Init and Apply (post)
        run: |
          terraform -chdir=./testSubAction-Code/post init -backend-config="key=SubscriptionCreation/${{ env.TF_VAR_subscription_name }}/post/terraform.tfstate"
          terraform -chdir=./testSubAction-Code/post apply -auto-approve
      
      - name: Mark env file as processed
        run: |
          python ./output_exports.py True

      - name: Commit and Push Changes
        run: |
          git config --local user.email "semal31@goutlook.com"
          git config --local user.name "Semal31"
          git add env_runs.json  # Update this to the path of the file that tracks processing status
          git commit -m "Update env_runs json" || echo "No changes to commit"
          git push